version: "3"
services:
  db:
    container_name: migrate_test_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ats
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    ports:
      - "5432:5432"

  api:
    container_name: api
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    # ホスト側のポート：コンテナのポート
    ports:
      - "3000:3000"
      # studio用のポート
      - "5555:5555"
    # ホスト側のsrcをコンテナのappにマウント
    # volumes:
      # - .:/app
      # - /packages/backend/node_modules
    # # 起動時のカレントフォルダ
    working_dir: /migrate-test/backend/packages/server
    # 起動後に実行するコマンド
    command: bash -c "cd ../prisma && npm run migrate:dev && echo y | npm run db:reset && cd ../../backend && npm run dev"
